// Plain node test script for scan.js — no test framework, no npm deps.
// Run with: node server/scan.test.js
//
// Builds a fixture tree under a temp dir and exercises scanSessions() twice
// (the second call must hit the in-memory cache and still be correct).

import assert from 'node:assert';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { scanSessions } from './scan.js';

const MIN_BYTES = 1500;

function line(obj) {
  return JSON.stringify(obj);
}

// Joins jsonl `lines` with newlines and, if the result is under `minBytes`,
// appends one more harmless filler line so the file comfortably clears the
// exclusion threshold.
function buildJsonl(lines, minBytes) {
  const body = lines.join('\n') + '\n';
  const currentBytes = Buffer.byteLength(body, 'utf8');
  if (currentBytes >= minBytes) return body;
  const need = minBytes - currentBytes + 50;
  const filler = line({ type: 'assistant', message: { content: 'p'.repeat(need) } });
  return body + filler + '\n';
}

const root = fs.mkdtempSync(path.join(os.tmpdir(), 'scan-test-'));

try {
  // --- Project dir A: caveat-wrapped first user line, then a real one ---
  const dirA = path.join(root, '-Users-test-repoA');
  fs.mkdirSync(dirA, { recursive: true });

  const caveatLines = [
    line({
      type: 'user',
      isSidechain: false,
      message: {
        content:
          '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>',
      },
      cwd: '/Users/test/repoA',
      sessionId: 'caveat-session',
      timestamp: '2026-07-10T00:00:00.000Z',
    }),
    line({
      type: 'user',
      isSidechain: false,
      message: { content: '  Fix the flaky retry logic in the payment worker  \n\n' },
      cwd: '/Users/test/repoA',
      sessionId: 'caveat-session',
      timestamp: '2026-07-10T00:00:05.000Z',
    }),
  ];
  const caveatFile = path.join(dirA, 'caveat-session.jsonl');
  fs.writeFileSync(caveatFile, buildJsonl(caveatLines, MIN_BYTES + 500));
  const tCaveat = new Date('2026-07-15T12:00:00.000Z');
  fs.utimesSync(caveatFile, tCaveat, tCaveat);

  // A file with a garbage non-JSON line mixed in — must not throw, and must
  // still find the real topic from the valid line that follows.
  const garbageLines = [
    '{this is not valid json at all!!',
    line({
      type: 'user',
      isSidechain: false,
      message: { content: 'Investigate why the nightly ETL job silently drops rows' },
      cwd: '/Users/test/repoA',
      sessionId: 'garbage-session',
      timestamp: '2026-07-12T00:00:00.000Z',
    }),
  ];
  const garbageFile = path.join(dirA, 'garbage-session.jsonl');
  fs.writeFileSync(garbageFile, buildJsonl(garbageLines, MIN_BYTES + 500));
  const tGarbage = new Date('2026-07-14T12:00:00.000Z');
  fs.utimesSync(garbageFile, tGarbage, tGarbage);

  // --- Project dir B: a summary line (must win over the user-text rule) ---
  const dirB = path.join(root, '-Users-test-repoB');
  fs.mkdirSync(dirB, { recursive: true });

  const summaryLines = [
    line({ type: 'summary', summary: 'Design the planet renderer camera controls', sessionId: 'summary-session' }),
    line({
      type: 'user',
      isSidechain: false,
      message: { content: 'irrelevant text that should be overridden by the summary line' },
      cwd: '/Users/test/repoB',
      sessionId: 'summary-session',
      timestamp: '2026-07-11T00:00:00.000Z',
    }),
  ];
  const summaryFile = path.join(dirB, 'summary-session.jsonl');
  fs.writeFileSync(summaryFile, buildJsonl(summaryLines, MIN_BYTES + 500));
  const tSummary = new Date('2026-07-13T12:00:00.000Z');
  fs.utimesSync(summaryFile, tSummary, tSummary);

  // An ai-title line (what current Claude Code emits) must also win rule 1.
  const aiTitleLines = [
    line({ type: 'ai-title', aiTitle: 'Build a session-scanner backend', sessionId: 'aititle-session' }),
    line({
      type: 'user',
      isSidechain: false,
      message: { content: 'user text that must lose to the ai-title line' },
      cwd: '/Users/test/repoB',
      sessionId: 'aititle-session',
      timestamp: '2026-07-11T01:00:00.000Z',
    }),
  ];
  const aiTitleFile = path.join(dirB, 'aititle-session.jsonl');
  fs.writeFileSync(aiTitleFile, buildJsonl(aiTitleLines, MIN_BYTES + 500));
  const tAiTitle = new Date('2026-07-13T13:00:00.000Z');
  fs.utimesSync(aiTitleFile, tAiTitle, tAiTitle);

  // A tiny session (< 1500 bytes) that must be excluded despite having an
  // otherwise perfectly valid topic + cwd.
  const tinyLines = [
    line({
      type: 'user',
      isSidechain: false,
      message: { content: 'short session' },
      cwd: '/Users/test/repoB',
      sessionId: 'tiny-session',
      timestamp: '2026-07-09T00:00:00.000Z',
    }),
  ];
  const tinyBody = tinyLines.join('\n') + '\n';
  assert.ok(Buffer.byteLength(tinyBody, 'utf8') < MIN_BYTES, 'fixture bug: tiny session must be under threshold');
  const tinyFile = path.join(dirB, 'tiny-session.jsonl');
  fs.writeFileSync(tinyFile, tinyBody);
  const tTiny = new Date('2026-07-08T12:00:00.000Z');
  fs.utimesSync(tinyFile, tTiny, tTiny);

  // --- First call ---
  const results1 = await scanSessions(root);

  assert.strictEqual(
    results1.length,
    4,
    `expected 4 sessions, got ${results1.length}: ${JSON.stringify(results1.map((s) => s.id))}`
  );

  const ids1 = results1.map((s) => s.id);
  assert.deepStrictEqual(
    ids1,
    ['caveat-session', 'garbage-session', 'aititle-session', 'summary-session'],
    'sessions must be sorted by lastActive desc'
  );

  const byId1 = Object.fromEntries(results1.map((s) => [s.id, s]));

  assert.strictEqual(
    byId1['caveat-session'].topic,
    'Fix the flaky retry logic in the payment worker',
    'must skip the <local-command-caveat> line and use the next real user line, trimmed+collapsed'
  );
  assert.strictEqual(byId1['caveat-session'].project, '/Users/test/repoA');

  assert.strictEqual(
    byId1['garbage-session'].topic,
    'Investigate why the nightly ETL job silently drops rows',
    'must skip the unparseable line without throwing and still extract the real topic'
  );
  assert.strictEqual(byId1['garbage-session'].project, '/Users/test/repoA');

  assert.strictEqual(
    byId1['summary-session'].topic,
    'Design the planet renderer camera controls',
    'a summary line must win over a valid user-text topic (rule 1 beats rule 2)'
  );
  assert.strictEqual(byId1['summary-session'].project, '/Users/test/repoB');

  assert.strictEqual(
    byId1['aititle-session'].topic,
    'Build a session-scanner backend',
    'an ai-title line must win over a valid user-text topic (rule 1 beats rule 2)'
  );
  assert.strictEqual(byId1['aititle-session'].project, '/Users/test/repoB');

  assert.ok(!('tiny-session' in byId1), 'tiny session must be excluded for being under the byte threshold');

  for (const s of results1) {
    assert.strictEqual(typeof s.id, 'string');
    assert.strictEqual(typeof s.project, 'string');
    assert.strictEqual(typeof s.topic, 'string');
    assert.ok(s.topic.length <= 80, 'topic must be truncated to 80 chars');
    assert.ok(!/[\n\r]/.test(s.topic), 'topic must be a single line');
    assert.strictEqual(typeof s.lastActive, 'number');
    assert.strictEqual(typeof s.bytes, 'number');
    assert.ok(s.bytes >= MIN_BYTES);
  }

  // --- Second call: must exercise the cache and return identical results ---
  const results2 = await scanSessions(root);
  assert.deepStrictEqual(results2, results1, 'second (cached) call must return identical results');

  console.log('scan.test.js: all assertions passed (%d sessions)', results1.length);
} finally {
  fs.rmSync(root, { recursive: true, force: true });
}
